[package]
name = "wasmer-examples/next-server-components-wasmer-starter"
version = "0.3.0"
description = "Next.js Server Componenents starter package"
readme = "README.md"
repository = "https://github.com/wasmer-examples/next-relay-wasmer-starter"

[dependencies]
"wasmer/winterjs" = "^0.4.4"

[fs]
"/web" = ".vercel/output/static"

[[command]]
name = "script"
module = "wasmer/winterjs:winterjs"
runner = "wasi"

[command.annotations.wasi]
main-args = ["--mode", "cloudflare", "/web"]
